# Generated by Django 5.1.3 on 2024-11-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AddField(
            model_name='user',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True, verbose_name='Groupe sanguin'),
        ),
        migrations.AddField(
            model_name='user',
            name='poids',
            field=models.FloatField(blank=True, null=True, verbose_name='Poids (kg)'),
        ),
        migrations.AddField(
            model_name='user',
            name='taille',
            field=models.FloatField(blank=True, null=True, verbose_name='Taille (cm)'),
        ),
    ]
