# Generated by Django 4.2.16 on 2024-11-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_adresse_user_code_postal_user_pays_user_ville_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tel",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Numéro de téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="adresse",
            field=models.CharField(max_length=255, verbose_name="Adresse postale"),
        ),
        migrations.AlterField(
            model_name="user",
            name="code_postal",
            field=models.CharField(max_length=10, verbose_name="Code postal"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Adresse mail"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pays",
            field=models.CharField(max_length=100, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="user",
            name="ville",
            field=models.CharField(max_length=100, verbose_name="Ville"),
        ),
    ]
