# Generated by Django 4.2.16 on 2024-11-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pharmacie",
            old_name="nom",
            new_name="name",
        ),
    ]
