# Generated by Django 4.2.16 on 2024-11-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0003_alter_pharmacie_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacie",
            name="slug",
            field=models.SlugField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
