# Generated by Django 4.2.16 on 2024-11-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0004_pharmacie_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacie",
            name="description",
            field=models.CharField(default="", max_length=3000),
            preserve_default=False,
        ),
    ]
