# Generated by Django 4.2.16 on 2024-11-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0005_pharmacie_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacie",
            name="ville",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
