# Generated by Django 5.1.3 on 2024-11-19 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_pharmacie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='ville',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
