# Generated by Django 4.2.16 on 2024-11-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0006_pharmacie_ville"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacie",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="users/logo_pharma.png",
                null=True,
                upload_to="p_pharmacies",
            ),
        ),
    ]
