# Generated by Django 5.1.3 on 2024-11-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='commentaires',
            field=models.TextField(blank=True, null=True),
        ),
    ]
