# Generated by Django 5.1.3 on 2024-11-20 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers', '0002_fichier_commentaires'),
        ('pharmacies', '0006_pharmacie_ville'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('traitee', 'Traité'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('drive_file_url', models.URLField(blank=True, null=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacies.pharmacie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Fichier',
        ),
    ]
