# Generated by Django 5.1.3 on 2024-11-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichiers', '0003_ordonnance_delete_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='nom_fichier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
